"""add auth_type to users

Revision ID: d428a772f942
Revises: 5f3c8a18dc7d
Create Date: 2025-11-17 15:44:39.988330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd428a772f942'
down_revision: Union[str, Sequence[str], None] = '5f3c8a18dc7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    auth_type = sa.Enum('AUTH0_PASSWORD', 'GOOGLE_OAUTH2', name='authtype')
    auth_type.create(op.get_bind())
    op.add_column(
        'users',
        sa.Column(
            'auth_type',
            auth_type,
            nullable=False,
            comment='Authentication type',
            server_default='AUTH0_PASSWORD',
        ),
    )
    op.alter_column('users', 'auth0_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Auth0 user identifier',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               comment='Primary email address',
               existing_nullable=True)
    op.drop_constraint(op.f('uq_users_auth0_id'), 'users', type_='unique')
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_auth0_id'), 'users', ['auth0_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               comment=None,
               existing_comment='Primary email address',
               existing_nullable=True)
    op.alter_column('users', 'auth0_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Auth0 user identifier',
               existing_nullable=False)
    op.drop_column('users', 'auth_type')
    # ### end Alembic commands ###
